spring.application.name=ms-cocina
server.port=8082

# Base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/db_cocina?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tu_password_aqui
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect